
#URL
url: "http://0.0.0.0:4000" # the base hostname & protocol for your sitetwitter_username: jasonkuruzovich
#url: "http://rpi-analytics.github.io" # the base hostname & protocol for your site
include: ['_pages']

# Site settings
title: "RPI Analytics"
course: "MGMT6963"
instructor: "Jason Kuruzovich"
course_title: "Technology Fundamentals for Business Analytics"
header-img: "img/1_header.png"
email: "kuruzj@rpi.edu"
description: "This is the official course website for the Technology Fundamentals of Business Analyitics Course"
baseurl: "/MGMT6963-2015" # the subpath of your site, e.g. /blog/
github_username:  "rpi-analytics"
twitter_username: "jasonkuruzovich"
linkedin_username: "jasonkuruzovich"


#Header Menu Settings
menu1: "Syllabus"
menu1_url: "/assets/MGMT6963_Fall2015_syllabus.pdf"
#If you aren't using Piazza, just comment this out.
menu2: "Piazza"
menu2_url: "https://piazza.com/rpi/fall2015/mgmt6963/home"
#This should be link to LMS. If not using LMS, comment out.
menu3: "Blackboard"
menu3_url: "https://lms9.rpi.edu:8443"
menu4: "Schedule"
menu4_url: "/pages/schedule"
menu5: "Projects"
menu5_url: "/pages/projects"
menu6: "Resources"
menu6_url: "/pages/resources"
#menu7: "Resources"
#menu7_url: "/resources"

wk1_meet: "1"
wk2_meet: ""
wk3_meet: "2"
wk4_meet: "3"
wk5_meet: "4"
wk6_meet: "5"
wk7_meet: "6"
wk8_meet: "7"
wk9_meet: "8"
wk10_meet: "9"
wk11_meet: "10"
wk12_meet: "11"
wk13_meet: "12"
wk14_meet: "13"
wk15_meet: "14"

wk1_date: "8/31"
wk2_date: "9/7"
wk3_date: "9/14"
wk4_date: "9/21"
wk5_date: "9/28"
wk6_date: "10/5"
wk7_date: "10/13"
wk8_date: "10/19"
wk9_date: "10/26"
wk10_date: "11/2"
wk11_date: "11/9"
wk12_date: "11/16"
wk13_date: "11/23"
wk14_date: "11/30"
wk15_date: "12/7"

wk1_topic: "The Rise of Analytics and the Tools of the Data Scientist"
wk2_topic: "No Classes - Labor Day"
wk3_topic: "Data Types and Structures"
wk4_topic: "Accessing and Processing Data"
wk5_topic: "Linking and Aggregating Data"
wk6_topic: "Missing Data and Introduction to Feature Creation"
wk7_topic: "Introduction to Modeling"
wk8_topic: "Introduction to Modeling II"
wk9_topic: "Midterm & Kaggle Project Presentations"
wk10_topic: "Introduction to Visualization"
wk11_topic: "Model Evaluation and Visualization"
wk12_topic: "Introduction to Text Mining"
wk13_topic: "Big Data with Spark"
wk14_topic: "Putting it All Together - Case Study"
wk15_topic: "Final Exam"

wk1_notes: "Start of Classes"
wk2_notes: ""
wk3_notes: "Add Deadline; Lab 1 due before class"
wk4_notes: "Lab 2 Due (Blackboard)"
wk5_notes: "Lab 3 Due (Blackboard)"
wk6_notes: "Lab 4 Due (Blackboard)"
wk7_notes: "Columbus Day/Class Tuesday Rather than Monday"
wk8_notes: "Kaggle 1 Assignment Due 10/23; 10/23 is Drop Deadline"
wk9_notes: ""
wk10_notes: "Guest Speaker Dave Geoghegan from Channel Eyes"
wk11_notes: ""
wk12_notes: ""
wk13_notes: ""
wk14_notes: "Kaggle 2 Assignment Due 11/30"
wk15_notes: ""







# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]