#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'
cookbook 'analyticsdojo', :path => "my-recipes/analyticsdojo"
cookbook 'yum', '~> 3.5.3'
cookbook 'apt', '~> 2.6.1'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'runit', '~> 1.5.18'
cookbook 'python', '~> 1.4.6'
cookbook 'java', '~> 1.31.0'
cookbook 'jekyll', '~> 0.1.0'
cookbook 'mongodb-10gen', '~> 0.4.1'
cookbook 'git', '~> 4.1.0'
cookbook 'vim', '~> 1.1.2'
cookbook 'nginx', '~> 2.7.6'
cookbook 'users', '~> 1.8.2'
cookbook 'gdebi', '~> 1.1.0'
cookbook 'users-auth', '~> 0.1.0'

#cookbook 'dashpot', :git => "https://github.com/g2webservices/chef-dashpot"
#cookbook 'tuning', :git => "https://github.com/g2webservices/chef-tuning"
#cookbook 'hadoop_cluster', '~> 3.0.5'
#cookbook 'hbase_cluster', '~> 3.0.4'
#cookbook 'apache_spark', '~> 1.2.1'
#cookbook 'apt', '~> 2.6.1'
#cookbook 'runit', '~> 1.5.18'
#cookbook 'yum', '~> 3.5.2'
#cookbook 'build-essential', '~> 2.1.3'
#cookbook 'python', '~> 1.4.6'
#cookbook 'git', '~> 4.1.0'
#cookbook 'smf', '~> 2.2.1'
#cookbook 'sqlite', '~> 1.1.0'
#cookbook 'mongodb', '~> 0.16.2'
#cookbook 'ipynb', '~> 1.1.0'
#cookbook 'nginx', '~> 2.7.4'
#cookbook 'users', '~> 1.7.0'
#cookbook 'scipy', '~> 0.3.1'
#cookbook 'database', '~> 3.1.0'
#cookbook 'hadoop', '~> 1.9.2'


#cookbook 'mysql', '~> 6.0.12'


#cookbook 'cookbook-rstudio',
#   :git => 'https://github.com/marsam/cookbook-rstudio.git'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
