source 'https://rubygems.org'

gem 'chefspec'
gem 'rspec'

group :integration do
  gem 'kitchen-vagrant'
  gem 'foodcritic'
  gem 'fauxhai'
end

group :development do
  gem "vagrant"
  gem 'busser-bats'
  gem 'busser-minitest'
  gem 'test-kitchen'
  gem 'berkshelf'
end

group :plugins do
  gem "vagrant-berkshelf"
  gem "vagrant-omnibus"
end
